[node]
working_dir = "/Volumes/BlockChain/subnet-alpha"
rpc_bind = "0.0.0.0:8044"
p2p_bind = "0.0.0.0:8045"
mining_key = "[private key]"
miner = true
mine_microblocks = true
local_peer_seed = "[private key]"
chain_id = [your chain id]

[miner]
first_attempt_time_ms = 60_000
subsequent_attempt_time_ms = 600_000
microblock_attempt_time_ms = 15_000

[burnchain]
chain = "stacks_layer_1"
mode = "subnet"
first_burn_header_height = 119_531
first_burn_header_hash = "9ba2f357115308fb1c503715f3a1b0cb3e8fdbe6baea7e7634635affdf675501"
contract_identifier = "ST3D03X5BHMNSAAW71NN7BQRMV4DW2G4JB3PXDYJG.subnet"
peer_host = "127.0.0.1"
rpc_port = 20443
peer_port = 20444
observer_port = 30445

