[node]
chain_id = 0x12345679
rpc_bind = "0.0.0.0:8054"
p2p_bind = "0.0.0.0:8055"
local_peer_seed = "029b65a8ee035c0c4c6850550f1aa432f2e2e61a91d0633efbb21c5abc19db8d90"
# data_url = "http://189.193.73.217:8054"
# p2p_address = "189.193.73.217:8055"
prometheus_bind = "0.0.0.0:9156"
working_dir = "/Users/Pato_Gomez/BlockChain/API-Environment/subnet-follower"
miner = false
bootstrap_node = "03f3c6caac2ee7abeac24145c717df4f49f185907c0f16de6885487d0f13c9ffc3@127.0.0.1:8045"





#[connection_options]
# public_ip_address = "189.193.73.217:8055"

[burnchain]
chain = "stacks_layer_1"
mode = "subnet"
first_burn_header_height = 125_753

contract_identifier = "ST3D03X5BHMNSAAW71NN7BQRMV4DW2G4JB3PXDYJG.subnet-v1"
peer_host = "127.0.0.1"
rpc_port = 18332
peer_port = 18333
observer_port = 30455
rpc_ssl = false
username = btcuser
password = btcpass
